### Authentication Service

@authToken = {{login.response.body.token}}
@user_id = 1

### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "AUser",
    "email": "user@example.com",
    "password": "yourpassword",
    "roles": ["USER","ADMIN"]
}

### Login
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "yourpassword"
}



### User Management

### Get Current User
GET http://localhost:8080/api/users/me
Authorization: Bearer {{authToken}}

### Get User by ID (Admin only)
GET http://localhost:8080/api/users/1
Authorization: Bearer {{authToken}}

### Update Current User
PUT http://localhost:8080/api/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Updated Name"
}

### Document Service

### Upload Document
POST http://localhost:8080/api/documents
Content-Type: multipart/form-data
Authorization: Bearer {{authToken}}
X-User-Id: {{user_id}}

// Form data:
// file: @/path/to/your/file
// description: Document description
// allowedUsers: ["user1", "user2"]

### Update Document
PUT http://localhost:8080/api/documents/1
Content-Type: multipart/form-data
Authorization: Bearer {{authToken}}
X-User-Id: {{user_id}}

// Form data:
// file: @/path/to/your/file (optional)
// description: Updated description (optional)
// allowedUsers: ["user1", "user2"] (optional)

### Get Document
GET http://localhost:8080/api/documents/1
Authorization: Bearer {{authToken}}

### Download Document
GET http://localhost:8080/api/documents/1/download
Authorization: Bearer {{authToken}}

### Delete Document
DELETE http://localhost:8080/api/documents/1
Authorization: Bearer {{authToken}}

### Get All Documents
GET http://localhost:8080/api/documents
Authorization: Bearer {{authToken}}

### Get User Documents
GET http://localhost:8080/api/documents/user
Authorization: Bearer {{authToken}}
X-User-Id: {{user_id}}

### Update Document Status
PATCH http://localhost:8080/api/documents/1/status?status=APPROVED
Authorization: Bearer {{authToken}}
X-User-Id: {{user_id}}