server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters: []

        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**
          filters:
            - name: JwtTokenFilter

        - id: email-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/email/**
          filters:
            - name: JwtTokenFilter

        - id: core-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/core/**
          filters:
            - name: JwtTokenFilter

        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: JwtTokenFilter

        - id: public-endpoints
          uri: http://localhost:8084
          predicates:
            - Path=/api/public/**
          filters: []

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: complitracker_jwt_secret_key_should_be_very_long_and_secure_in_production
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      authCircuitBreaker:
        baseConfig: default
      documentCircuitBreaker:
        baseConfig: default
      emailCircuitBreaker:
        baseConfig: default
      coreCircuitBreaker:
        baseConfig: default