global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8080']

  - job_name: 'document-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['document-service:8080']

  - job_name: 'email-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['email-service:8080']

  - job_name: 'core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-service:8080']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']