name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build and Test Services
      run: |
        cd api-gateway && ./mvnw clean package
        cd ../services/auth-service && ./mvnw clean package
        cd ../document-service && ./mvnw clean package
        cd ../email-service && ./mvnw clean package
        cd ../core-service && ./mvnw clean package

    - name: Build and Push Docker Images
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
        docker build -t complitracker/api-gateway:latest ./api-gateway
        docker push complitracker/api-gateway:latest
        
        docker build -t complitracker/auth-service:latest ./services/auth-service
        docker push complitracker/auth-service:latest
        
        docker build -t complitracker/document-service:latest ./services/document-service
        docker push complitracker/document-service:latest
        
        docker build -t complitracker/email-service:latest ./services/email-service
        docker push complitracker/email-service:latest
        
        docker build -t complitracker/core-service:latest ./services/core-service
        docker push complitracker/core-service:latest

    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        
        kubectl apply -f infrastructure/kubernetes/
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}